# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/reviews.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/reviews.proto',
  package='sample.reviews',
  syntax='proto3',
  serialized_pb=_b('\n\x13proto/reviews.proto\x12\x0esample.reviews\"<\n\x06Review\x12\x10\n\x08reviewer\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x12\n\nratingstar\x18\x03 \x01(\x03\"\'\n\x12\x42ookReviewsRequest\x12\x11\n\tproductId\x18\x01 \x01(\x03\"Q\n\x13\x42ookReviewsResponse\x12\x11\n\tproductId\x18\x01 \x01(\x03\x12\'\n\x07reviews\x18\x02 \x03(\x0b\x32\x16.sample.reviews.Review2g\n\x07Reviews\x12\\\n\x0f\x42ookReviewsById\x12\".sample.reviews.BookReviewsRequest\x1a#.sample.reviews.BookReviewsResponse\"\x00\x42%\n\x13sample.reviews.grpcB\x0cReviewsProtoP\x01\x62\x06proto3')
)




_REVIEW = _descriptor.Descriptor(
  name='Review',
  full_name='sample.reviews.Review',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reviewer', full_name='sample.reviews.Review.reviewer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='sample.reviews.Review.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ratingstar', full_name='sample.reviews.Review.ratingstar', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=99,
)


_BOOKREVIEWSREQUEST = _descriptor.Descriptor(
  name='BookReviewsRequest',
  full_name='sample.reviews.BookReviewsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='productId', full_name='sample.reviews.BookReviewsRequest.productId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=140,
)


_BOOKREVIEWSRESPONSE = _descriptor.Descriptor(
  name='BookReviewsResponse',
  full_name='sample.reviews.BookReviewsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='productId', full_name='sample.reviews.BookReviewsResponse.productId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reviews', full_name='sample.reviews.BookReviewsResponse.reviews', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=223,
)

_BOOKREVIEWSRESPONSE.fields_by_name['reviews'].message_type = _REVIEW
DESCRIPTOR.message_types_by_name['Review'] = _REVIEW
DESCRIPTOR.message_types_by_name['BookReviewsRequest'] = _BOOKREVIEWSREQUEST
DESCRIPTOR.message_types_by_name['BookReviewsResponse'] = _BOOKREVIEWSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Review = _reflection.GeneratedProtocolMessageType('Review', (_message.Message,), dict(
  DESCRIPTOR = _REVIEW,
  __module__ = 'proto.reviews_pb2'
  # @@protoc_insertion_point(class_scope:sample.reviews.Review)
  ))
_sym_db.RegisterMessage(Review)

BookReviewsRequest = _reflection.GeneratedProtocolMessageType('BookReviewsRequest', (_message.Message,), dict(
  DESCRIPTOR = _BOOKREVIEWSREQUEST,
  __module__ = 'proto.reviews_pb2'
  # @@protoc_insertion_point(class_scope:sample.reviews.BookReviewsRequest)
  ))
_sym_db.RegisterMessage(BookReviewsRequest)

BookReviewsResponse = _reflection.GeneratedProtocolMessageType('BookReviewsResponse', (_message.Message,), dict(
  DESCRIPTOR = _BOOKREVIEWSRESPONSE,
  __module__ = 'proto.reviews_pb2'
  # @@protoc_insertion_point(class_scope:sample.reviews.BookReviewsResponse)
  ))
_sym_db.RegisterMessage(BookReviewsResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\023sample.reviews.grpcB\014ReviewsProtoP\001'))

_REVIEWS = _descriptor.ServiceDescriptor(
  name='Reviews',
  full_name='sample.reviews.Reviews',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=225,
  serialized_end=328,
  methods=[
  _descriptor.MethodDescriptor(
    name='BookReviewsById',
    full_name='sample.reviews.Reviews.BookReviewsById',
    index=0,
    containing_service=None,
    input_type=_BOOKREVIEWSREQUEST,
    output_type=_BOOKREVIEWSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REVIEWS)

DESCRIPTOR.services_by_name['Reviews'] = _REVIEWS

# @@protoc_insertion_point(module_scope)
