# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import reviews_pb2 as proto_dot_reviews__pb2


class ReviewsStub(object):
  """import "google/protobuf/empty.proto";

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.BookReviewsById = channel.unary_unary(
        '/sample.reviews.Reviews/BookReviewsById',
        request_serializer=proto_dot_reviews__pb2.BookReviewsRequest.SerializeToString,
        response_deserializer=proto_dot_reviews__pb2.BookReviewsResponse.FromString,
        )


class ReviewsServicer(object):
  """import "google/protobuf/empty.proto";

  """

  def BookReviewsById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ReviewsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'BookReviewsById': grpc.unary_unary_rpc_method_handler(
          servicer.BookReviewsById,
          request_deserializer=proto_dot_reviews__pb2.BookReviewsRequest.FromString,
          response_serializer=proto_dot_reviews__pb2.BookReviewsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sample.reviews.Reviews', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
